ignored = ["jba.io/go/auth","jba.io/go/httputils"]

[[dependencies]]
  branch = "master"
  name = "github.com/boltdb/bolt"

[[dependencies]]
  branch = "master"
  name = "github.com/dimfeld/httptreemux"

[[dependencies]]
  branch = "master"
  name = "github.com/disintegration/imaging"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/csrf"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/handlers"

[[dependencies]]
  branch = "master"
  name = "github.com/justinas/alice"

[[dependencies]]
  branch = "master"
  name = "github.com/kennygrant/sanitize"

[[dependencies]]
  branch = "master"
  name = "github.com/oxtoacart/bpool"

[[dependencies]]
  branch = "master"
  name = "github.com/russross/blackfriday"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/viper"
