# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["jba.io/go/auth","jba.io/go/httputils"]

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "~1.6.1"

[[constraint]]
  name = "github.com/disintegration/imaging"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/csrf"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/kennygrant/sanitize"
  version = "1.2.3"

[[constraint]]
  branch = "master"
  name = "github.com/oxtoacart/bpool"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.5"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"
