#!/bin/sh

case "$1" in 
    upgrade)
    ;;  
    remove)
        deb-systemd-helper disable gothing.service >/dev/null
        deb-systemd-invoke stop gothing.service >/dev/null
    ;;
    *)
    ;;
esac

exit 0